name: Build & Test

on:
  pull_request:
    branches: [ master-dev ]

jobs:
  build-lib:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.konan*') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Building lib
        run: |
          chmod +x ./gradlew
          ./gradlew build
        working-directory: .
